api_register:
    path: /register/{username}/{password}/{email}/{birthday}/{role}/{firstName}/{lastName}/{phone}
    defaults: {_controller: AppBundle:User:register}
api_edit:
    path: /edit/{id}/{username}/{password}/{email}/{birthday}/{role}/{firstName}/{lastName}/{phone}
    defaults: {_controller: AppBundle:User:edit}
api_login:
    path: /login/{username}/{password}
    defaults: {_controller: AppBundle:User:login}
api_user_read:
    path: /user/{id}
    defaults: {_controller: AppBundle:User:read}
api_user_readall:
    path: /user
    defaults: {_controller: AppBundle:User:readAll}
api_coach_readall:
    path: /coach
    defaults: {_controller: AppBundle:User:readAllCoach}
api_username_exist:
    path: /usernameExist/{username}
    defaults: {_controller: AppBundle:User:usernameExist}
api_email_exist:
    path: /emailExist/{email}
    defaults: {_controller: AppBundle:User:emailExist}
api_room_create:
    path: /room/{name}/{description}/{image}
    defaults: {_controller: AppBundle:Room:create}
api_room_update:
    path: /room/{id}/{name}/{description}/{image}
    defaults: {_controller: AppBundle:Room:update}
api_room_read:
    path: /room/{id}
    defaults: {_controller: AppBundle:Room:read}
api_room_readall:
    path: /room
    defaults: {_controller: AppBundle:Room:readAll}
api_room_delete:
    path: /room/delete/{id}
    defaults: {_controller: AppBundle:Room:delete}
api_session_create:
    path:     /session/{name}/{date}/{duration}/{location}/{currentNb}/{maxNb}
    defaults: { _controller: AppBundle:Session:create }
api_session_update:
    path:     /session/{id}/{name}/{date}/{duration}/{location}/{currentNb}/{maxNb}
    defaults: { _controller: AppBundle:Session:update }
api_session_read:
    path:     /session/{id}
    defaults: { _controller: AppBundle:Session:read }
api_session_read_all:
    path:     /session
    defaults: { _controller: AppBundle:Session:readAll }
api_session_delete:
    path:     /session/delete/{id}
    defaults: { _controller: AppBundle:Session:delete }
api_participation_create:
    path:     /Participation/add/{user}/{session}
    defaults: { _controller: AppBundle:Participation:create }
api_participation_remove:
    path:     /Participation/rem/{user}/{session}
    defaults: { _controller: AppBundle:Participation:remove }
api_my_participation:
    path:     /myParticipation/{user}
    defaults: { _controller: AppBundle:Participation:myParticipation }
api_my_participation_count:
    path:     /myParticipationCount/{user}
    defaults: { _controller: AppBundle:Participation:myParticipationCount }
api_profile_add:
    path:     /profile/{user_id}/{gender}/{weight}/{height}/{image}
    defaults: { _controller: AppBundle:Profile:add }
api_profile_update:
    path:     /profileUpdate/{id}/{gender}/{weight}/{height}
    defaults: { _controller: AppBundle:Profile:update }
api_profile_read:
    path:     /profile/{id}
    defaults: { _controller: AppBundle:Profile:read }
api_profile_read_all:
    path:     /profile
    defaults: { _controller: AppBundle:Profile:readall }
api_post_add:
    path:     /Post/add/{Title}/{Image}/{Content}
    defaults: { _controller: AppBundle:Post:Add }
api_post_remove:
    path:     /Post/remove/{id}
    defaults: { _controller: AppBundle:Post:Remove }
api_post_list:
    path:     /Post/list
    defaults: { _controller: AppBundle:Post:list }
api_post_edit:
    path:     /Post/edit/{id}/{Title}/{Image}/{Content}
    defaults: { _controller: AppBundle:Post:Edit }