api_register:
    path: /register/{username}/{password}/{email}/{birthday}/{role}/{firstName}/{lastName}/{phone}
    defaults: {_controller: AppBundle:User:register}
api_login:
    path: /login/{username}/{password}
    defaults: {_controller: AppBundle:User:login}
