AppBundle\Entity\Profile:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
      user:
        targetEntity: User
        inversedBy: Profile
        joinColumn:
          name: user_id
          referencedColumnName: id
    fields:
        gender:
            type: string
            length: 255
        weight:
            type: float
        height:
            type: float
        image:
            type: string
            length : 255
    lifecycleCallbacks: {  }
