AppBundle\Entity\Session:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SessionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        date:
            type: datetime
        duration:
            type: string
            length: 255

        currentNb:
            type: integer
            nullable: true
        maxNb:
            type: integer
            nullable: true
    manyToOne:
        location:
            targetEntity: Room
            inversedBy: Session
            joinColumn:
                name: room_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
