<?php

namespace AppBundle\Repository;

/**
 * trainingSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trainingSessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTrainingSessionByUser($idUser)
    {
        $query=$this->getEntityManager()
            ->createQuery("
            select p from AppBundle:trainingSession p
            WHERE p.idUser=:id")
            ->setParameter('id',$idUser);
        return $query->getResult();
    }

}
