<?php

namespace AppBundle\Repository;

/**
 * trainingSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trainingSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
